[package]
name = "watchdir"
version = "0.1.0"
authors = ["rydesun <rydesun@gmail.com>"]
license = "MIT"
description = "A tool to watch directories in which files were created"
homepage = "https://github.com/rydesun/watchdir"
repository = "https://github.com/rydesun/watchdir"
keywords = ["cli", "inotify", "linux"]
categories = ["command-line-utilities"]
edition = "2018"
publish = false

[dependencies]
clap = "3.0.0-beta.4"
libc = "0.2"
walkdir = "2"
snafu = "0.6"
tracing = "0.1"
tracing-subscriber = "0.2"
termcolor = "1.1"
ahash = "0.7"

[dev-dependencies]
tempfile = "3"
rand = "0.8"

[build-dependencies]
chrono = "0.4"
